name: flutter_stv_kit
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6
  device_preview: ^1.2.0
  go_router: ^14.1.4
  flutter_riverpod: ^2.5.1
  import_sorter: ^4.6.0
  gap: ^3.0.1
  font_awesome_flutter: ^10.7.0
  form_field_validator: ^1.1.0
  top_snackbar_flutter: ^3.1.0
  bart: ^1.4.0
  slang: ^3.31.0
  slang_flutter: ^3.31.0
  freezed: ^2.5.2
  freezed_annotation: ^2.4.1
  riverpod_generator: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner:
  flutter_gen_runner:
  slang_build_runner: ^3.31.0
  json_serializable: ^6.8.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: NotoSansJp
      fonts:
        - asset: assets/fonts/NotoSansJP-Regular.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf

flutter_gen:
  output: lib/gen/
  line_length: 80
